spring.application.name=healthbridge-backend

server.port=8088

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://hirunahansindugamage_db_user:4iSJFnCbtvECylD5@ac-5pyc1nb-shard-00-00.2tysxzi.mongodb.net:27017,ac-5pyc1nb-shard-00-01.2tysxzi.mongodb.net:27017,ac-5pyc1nb-shard-00-02.2tysxzi.mongodb.net:27017/?ssl=true&replicaSet=atlas-q3tlbn-shard-0&authSource=admin&appName=Cluster0
spring.data.mongodb.database=health-bridge-dev
spring.mongodb.uri=mongodb+srv://hirunahansindugamage_db_user:4iSJFnCbtvECylD5@cluster0.2tysxzi.mongodb.net/healthbridge?appName=Cluster0
spring.mongodb.database=health-bridge-dev

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=healthbridge012@gmail.com
spring.mail.password=oyrzklryrnzyojeq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2 TLSv1.3
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000


# Google OAuth Configuration
google.client.id=${GOOGLE_CLIENT_ID:your_google_client_id.apps.googleusercontent.com}
google.client.secret=${GOOGLE_CLIENT_SECRET:your_google_client_secret}
